spring:
  application:
    name: wow-server
  profiles:
    active: local
server:
  port: 8787

management:
  endpoints:
    web:
      exposure:
        include: health,configprops
  endpoint:
    health:
      show-details: always