spring:
  datasource:
    url: jdbc:postgresql://34.72.94.112:5432/postgres
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${jdbcpassword}
    jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      connection-timeout: 30000
      minimum-idle: 20
      maximum-pool-size: 300
      max-lifetime: 180000
